name: Build and Deploy to Azure

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Récupération du Code
      uses: actions/checkout@v3

    - name: Connexion à Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    # On utilise la méthode "az acr build" qui est plus robuste
    # et qui n'a pas besoin de mot de passe compliqué.
    - name: Build & Push Docker Image
      run: |
        az acr build --registry ${{ secrets.ACR_NAME }} --image ${{ secrets.APP_NAME }}:${{ github.sha }} .

    - name: Déploiement sur Container App
      uses: azure/container-apps-deploy-action@v1
      with:
        appSourcePath: ${{ github.workspace }}
        acrName: ${{ secrets.ACR_NAME }}
        containerAppName: ${{ secrets.APP_NAME }}
        resourceGroup: ${{ secrets.RESOURCE_GROUP }}
        imageToDeploy: ${{ secrets.ACR_NAME }}.azurecr.io/${{ secrets.APP_NAME }}:${{ github.sha }}
